# Generated by Django 2.1.7 on 2020-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(default='github', max_length=16)),
                ('location', models.CharField(default='github', max_length=256)),
            ],
        ),
    ]
