# Generated by Django 2.1.7 on 2020-02-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openblog',
            name='blog_type',
        ),
        migrations.RemoveField(
            model_name='openblog',
            name='location',
        ),
        migrations.AddField(
            model_name='openblog',
            name='blog_info',
            field=models.CharField(default='github', max_length=512),
        ),
    ]
