# Generated by Django 2.1.7 on 2020-02-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_list', '0002_auto_20200222_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openblog',
            name='id',
        ),
        migrations.AddField(
            model_name='openblog',
            name='blog_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
